projects = {
    1 :  'FP tutor',
    2 :  'Tuiles multimédia 3D sur le web',
    3 :  'Algorithme pour gagner à Hanabi',
    4 :  'Planification de mouvement pour robots',
    5 :  'Clicodrome pour lexique électronique',
    6 :  'Application météo décalée pour Android',
    7 :  'Spatialisation par le geste',
    8 :  'Visualisations de traces d\'exécution pour l\'aide au débugage et à l\'analyse d\'application hautes performances',
    9 :  "Développement sur radio-logicielle d'une passerelle LoRa améliorée",
    10 :  "Environement 'Amstrad CPC' pour la bibliothèque d'apprentissage par renforcement 'OpenAI-Gym'",
    11 :  "Génération de playlistes musicales pour un groupe d'utilisateurs",
    12 :  "Les processus de décision: d'ou vient la difficulté",
    13 :  'Localisation de robots en présence de faux positifs',
    14 :  'Suivi de robots pour annotation semi-automatique',
    15 :  'Bibliothèque python pour la création de dégradation d\'images de documents pour un utilisation en deep learning',
    16 :  "Analyse d'architecture logicielles : couplage et cohésion en C++",
    17 :  "Analyse d'architecture logicielles : stabilité en Java",
    18 :  'Slitherlnk: IA pour la résolution d\'un jeu géométrique',
    19 :  "Réalisation d'un environnement d'exécution y86+HCL en Python ou en node.JS",
    20 :  'Joueur de Scrabble',
    21 :  'Génération procédurale de planètes sphériques',
    22 :  'IA pour un jeu de Capture the Flag temps réel en python',
    23 : 'Personal Hypno Vibes 2',
    24 : 'Visualisation de tâches hiérarchiques',
    25 : 'Calcul de cycles hamiltoniens dans des graphes fullerènes'
}